### ISSUE TITLE
Call to alarm() is lost on restart

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#106]
For the following program:

    #include <unistd.h>
    int main() {
      alarm(15);
      while (1);
      return 0;}
Try:

    dmtcp_launch -i3 ./a.out
    dmtcp_restart ckpt_a.out_*.dmtcp
and wait 15 seconds to see if the alarm will kill the process.  It doesn't.

The timer plugin works.  So, why not this?

**Comment by rohgarg** [comment]
Closed via https://github.com/dmtcp/dmtcp/commit/29d7e3c473724ea4aebe2c0a284225cf2ac0b0a4
