### ISSUE TITLE
Release 3.0, Windows Subsystem for Linux with Ubuntu 22.04 LTS: restart doesn't work

### ISSUE THREAD

**Issue by thomas-maeder** [dmtcp/dmtcp#1088]
$ ../dmtcp-3.0.0/bin/dmtcp_restart ckpt_py_65c44f5bb73e5c66-40000-1dca9c2374fc.dmtcp
[22731] mtcp_restart.c:347 restore_brk:
  error: new/current break (0x11213000) != saved break (0x7fffb84f4000)
[22731] mtcp_util.c:844 mmap_fixed_noreplace:
  error 95 mapping 0x800000 bytes at 0x7fffbf930000, flags: 0x122, prot :0x3
[22731] mtcp_restart.c:1115 read_one_memory_area:
  Assertion failed: mmappedat == area.addr
Segmentation fault (core dumped)

I have successfully restarted the same software on a regular Ubuntu 22.04 LTS.

**Comment by gc00** [comment]
Please refer to Issue #1087.  You appear to have opened two issues on the same topic.  I will close this issue, since it's a dupicate.
