### ISSUE TITLE
restart fails for `stress`

### ISSUE THREAD

**Issue by rohgarg** [dmtcp/dmtcp#126]
Here are the steps to reproduce:
```Bash
$ dmtcp_launch stress --vm 2 --vm-bytes 128M --timeout 30s
$ dmtcp_command -cb
$ dmtcp_command -k
$ ./dmtcp_restart_script.sh
```
Restart gets stuck and the program never finishes.

**Comment by gc00** [comment]
@rohgarg: Could you give us a pointer to this program `stress`?

**Comment by rohgarg** [comment]
@gc00: I looked at the `stress` program's source. It's basically an infinite loop and the only way out of it is a time-out. Unfortunately, it uses `alarm()` to set up time-out. The program is restarted correctly but appears to be "stuck" on restart because DMTCP fails to restore the alarm. This is a known issue: #106.

**Comment by rohgarg** [comment]
Fixed via https://github.com/dmtcp/dmtcp/commit/29d7e3c473724ea4aebe2c0a284225cf2ac0b0a4
