### ISSUE TITLE
dmtcp_get_restart_env() w/ --modify-env fails if no such env var

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#149]
A DMTCP user reported the following bug.  I've reproduced it, but won't have time to do a pull request fo tix it over the next few days.  So, in case someone else can get to it first.  ...  It should be easy to fix.

The issue is that a call to dmtcp_get_restart_env() will make reference to a file `dmtcp_env.txt` upon restart.  If the environment variables inside `dmtcp_env.txt` exist, there's no problem.  But when an environment variable doesn't exist, our documentation says that we should return `-1`.  Instead, we crash with the following `JASSERT`. 
    
    % bin/dmtcp_restart ckpt_a.out_12ec77b5d69-40000-55acb4dd.dmtcp
    Host: login  (129.10.117.100)
    Port: 7779
    Checkpoint Interval: disabled (checkpoint manually instead)
    Exit on last client: 1
    Backgrounding...
    [40000] ERROR at dmtcpplugin.cpp:403 in dmtcp_get_restart_env;     REASON='JASSERT(env_end_ptr > env_buf || env_buf[0] == '\0') failed'
         (char *)env_buf = USER=gene
    a.out (40000): Terminating...`

**Comment by rohgarg** [comment]
Fixed by #151
