### ISSUE TITLE
Have an error while using SLURM

### ISSUE THREAD

**Issue by zhixuanc** [dmtcp/dmtcp#150]
I was referring to https://github.com/dmtcp/dmtcp/blob/master/plugin/batch-queue/job_examples/ccr_buffalo/slurm_dmtcp_ompi_tcp
to submit remote parallel computation jobs. The computational source that I am using is also CCR at Buffalo. The only modification that I made is the replace 
srun dmtcp_launch --quiet --rm -i $nTics $EXE $ARGS 1>${OUTFILE} 2>${ERRFILE}
with 
dmtcp_launch --quiet --rm --infiniband -i $nTics mpirun $ARGS $EXE 1>${OUTFILE} 2>${ERRFILE}

But I got the following error:
[46000] WARNING at kernelbufferdrainer.cpp:124 in onTimeoutInterval; REASON='JWARNING(false) failed'
     _dataSockets[i]->socket().sockfd() = 8
     buffer.size() = 0
     WARN_INTERVAL_SEC = 10
Message: Still draining socket... perhaps remote host is not running under DMTCP?

Could you help me on that.

**Comment by jiajuncao** [comment]
Why did you need to remove the srun prefix? Also, have you tried removing the whole dmtcp related prefix to see if the job can be launched correctly, i.e., replacing the command with

mpirun $ARGS $EXE 1>${OUTFILE} 2>${ERRFILE}

as a sanity test?

**Comment by zhixuanc** [comment]
Thank you very much for replying.

1)mpirun $ARGS $EXE 1>${OUTFILE} 2>${ERRFILE} works well.
2) I was always submitting my job with mpirun. Unfortunately, I encountered some error when I submit jobs with sun(even without dmtcp)… So I was using mpirun. That’s why I did not use srun.
3) When I just submit jobs with dmtcp_launch -i 600 mpirun $ARGS $EXE 1>${OUTFILE} 2>${ERRFILE}, it works well. ——>But have trouble when I tried to restart from the checkpoint using ./restart_script

**Comment by jiajuncao** [comment]
I'm not sure if you're using it correctly (it's been a while since I tested OpenMPI at Buffalo last time). However, to run it using srun, I think you need to tell where the pmi library is, and I don't know the OpenMPI installed at Buffalo has Slurm support for srun. Another way to try it would be to follow their user guide: https://www.buffalo.edu/ccr/support/software-resources/mpi-multi-threaded/open-mpi.html
In the example, it passes a bunch of environment variables to OpenMPI to launch the job on correct nodes and processors.

**Comment by zhixuanc** [comment]
Well, my code works well with openMPI on CCR(Buffalo) without using dmtcp.
I was submitting jobs with slurm script (using mpirun instead of srun) and
it did work.
But when I tried to use dmtcp, I had some trouble. So I believe the issue I
did not use dmtcp correctly. I have been searching for helps by google, but
it seems that there isn't enough information about dmtcp on websits. That's
why I contacted you. I would be really appreciate it if you can provide
some help. If you need more information to figure out what's wrong, just
let me know.
Thank you again.

On Tue, Jul 21, 2015 at 6:26 PM, jiajuncao <notifications@github.com> wrote:

> I'm not sure if you're using it correctly (it's been a while since I
> tested OpenMPI at Buffalo last time). However, to run it using srun, I
> think you need to tell where the pmi library is, and I don't know the
> OpenMPI installed at Buffalo has Slurm support for srun. Another way to try
> it would be to follow their user guide:
> https://www.buffalo.edu/ccr/support/software-resources/mpi-multi-threaded/open-mpi.html
> In the example, it passes a bunch of environment variables to OpenMPI to
> launch the job on correct nodes and processors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmtcp/dmtcp/issues/150#issuecomment-123497795>.
>



-- 
Zhixuan Cao
Mechanical Engineering, University at Buffalo SUNY

**Comment by jiajuncao** [comment]
How did you do the restart? I suppose you should also use the submission script?

**Comment by zhixuanc** [comment]
Actually, I tried two ways to submit my jobs, one with slurm script,
another through command line interactively.

1) When I try to submit job with slurm script, I would have error and not
able to generate restart script (.sh file).  Let alone restart from the
checkpoint.
The error message is:
 Message: Still draining socket... perhaps remote host is not running under
DMTCP?
[46000] WARNING at kernelbufferdrainer.cpp:124 in onTimeoutInterval;
REASON='JWARNING(false) failed'
     _dataSockets[i]->socket().sockfd() = 8
     buffer.size() = 0
     WARN_INTERVAL_SEC = 10


2)I also tried submite jobs through command line instead of using the slurm
scritp. What I did to submit jobs through command line is : First request
for some compuational sources (4 nodes, 72 hours, for example), then type
the following command in linux bash:
dmtcp_launch -i 600 mpirun $ARGS $EXE 1>${OUTFILE} 2>${ERRFILE}
In this case, there is no erro and all files includes restart files will be
generated. But I can not restart when I type: ./dmtcp_restart_script.sh

On Tue, Jul 21, 2015 at 7:23 PM, jiajuncao <notifications@github.com> wrote:

> How did you do the restart? I suppose you should also use the submission
> script?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmtcp/dmtcp/issues/150#issuecomment-123506371>.
>



-- 
Zhixuan Cao
Mechanical Engineering, University at Buffalo SUNY

**Comment by jiajuncao** [comment]
I'll run a few tests tonight to see if it works. Will let you know tomorrow.

**Comment by jiajuncao** [comment]
Can you try adding the --mpi=pmi2 option to srun, e.g., replace
srun dmtcp_launch --quiet --rm -i $nTics $EXE $ARGS 1>${OUTFILE} 2>${ERRFILE}
with
srun --mpi=pmi2 dmtcp_launch --quiet --rm -i $nTics $EXE $ARGS 1>${OUTFILE} 2>${ERRFILE}

**Comment by zhixuanc** [comment]
Thank you, it is better this time as it can run and have some output. Previously, I can not use run at all, my tasks could not be launched if I use srun. You have already helped me. But this time I still have the following error message which is different from previous one

dmtcp_coordinator starting...
    Host: d09n04s02 (10.104.9.104)
    Port: 7779
    Checkpoint Interval: 600
    Exit on last client: 1
dmtcp_coordinator starting...
    Host: d09n05s02 (10.104.9.105)
    Port: 7779
    Checkpoint Interval: dmtcp_coordinator starting...
    Host: d09n08s02 (10.104.9.108)
    Port: 7779
    Checkpoint Interval: dmtcp_coordinator starting...
    Host: d09n13s02 (10.104.9.113)
    Port: 7779
    Checkpoint Interval: 600
    Exit on last client: 1
600
    Exit on last client: 1
600
    Exit on last client: 1
[cli_0]: write_line error; fd=12 buf=:cmd=barrier_in
:
system msg for write_line failure : Bad file descriptor
srun: error: d09n04s02: task 0: Exited with exit code 99
[cli_2]: write_line error; fd=12 buf=:cmd=barrier_in
:
system msg for write_line failure : Bad file descriptor
[cli_3]: write_line error; fd=12 buf=:cmd=barrier_in
:
system msg for write_line failure : Bad file descriptor
srun: error: d09n13s02: task 3: Exited with exit code 99
srun: error: d09n08s02: task 2: Exited with exit code 99
[cli_1]: write_line error; fd=12 buf=:cmd=barrier_in
:
system msg for write_line failure : Bad file descriptor
srun: error: d09n05s02: task 1: Exited with exit code 99

**Comment by jiajuncao** [comment]
Did you run it interactively or using the submission script? My solution applies for the script approach. If you use "sbatch script", the coordinator shouldn't be launched on all computing nodes.

**Comment by zhixuanc** [comment]
I was using submission script. Replace the old command 
dmtcp_launch --quiet --rm -i $nTics mpirun $ARGS $EXE 1>${OUTFILE} 2>${ERRFILE}
with the new one:
srun --mpi=pmi2 dmtcp_launch --quiet --rm -i $nTics $EXE $ARGS 1>${OUTFILE} 2>${ERRFILE}

and got that error message.

**Comment by jiajuncao** [comment]
That's odd. On which machine did you submit the script? The login node or some machine allocated using salloc or srun?

**Comment by zhixuanc** [comment]
I was on the login node (rush) when I submit my slurm script with sbatch script-name.

**Comment by jiajuncao** [comment]
Interesting. I just tested using the same method, and it worked. Can you put your submission script somewhere or paste it here? I need to sleep now, and will get back to you tomorrow.

**Comment by zhixuanc** [comment]
I am attaching the script. If you need more information, just let me know. 

Have a nice night.

Zhixuan Cao

**Comment by jiajuncao** [comment]
Hi Zhixuan,

Could you please sign up an account for Slack? It's a very convenient tool for teamwork. Go to https://dmtcp.slack.com, and the registration can be finished shortly. I think we can discuss more technical details there.

**Comment by zhixuanc** [comment]
I have alreay registered. My user name is zhixuanc_dmtcp
The email I am using is zhixuanc@buffalo.edu

what is the password to sign into dmtcp.slack.com. I tried to use my own
password, it is incorrect.


On Wed, Jul 22, 2015 at 11:13 AM, jiajuncao <notifications@github.com>
wrote:

> Hi Zhixuan,
>
> Could you please sign up an account for Slack? It's a very convenient tool
> for teamwork. Go to https://dmtcp.slack.com, and the registration can be
> finished shortly. I think we can discuss more technical details there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmtcp/dmtcp/issues/150#issuecomment-123754462>.
>



-- 
Zhixuan Cao
Mechanical Engineering, University at Buffalo SUNY

**Comment by zhixuanc** [comment]
I think I need your invitation to join the team dmtcp

On Wed, Jul 22, 2015 at 11:30 AM, Zhixuan Cao <zhixuanc@buffalo.edu> wrote:

> I have alreay registered. My user name is zhixuanc_dmtcp
> The email I am using is zhixuanc@buffalo.edu
>
> what is the password to sign into dmtcp.slack.com. I tried to use my own
> password, it is incorrect.
>
>
> On Wed, Jul 22, 2015 at 11:13 AM, jiajuncao <notifications@github.com>
> wrote:
>
>> Hi Zhixuan,
>>
>> Could you please sign up an account for Slack? It's a very convenient
>> tool for teamwork. Go to https://dmtcp.slack.com, and the registration
>> can be finished shortly. I think we can discuss more technical details
>> there.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dmtcp/dmtcp/issues/150#issuecomment-123754462>.
>>
>
>
>
> --
> Zhixuan Cao
> Mechanical Engineering, University at Buffalo SUNY
>



-- 
Zhixuan Cao
Mechanical Engineering, University at Buffalo SUNY

**Comment by gc00** [comment]
Hi @zhixuanc , we may have dropped the ball on this one.  I've now issued an invite to you, on slack.  @jiajuncao, what is the status on this issue with SLURM?  Is there more progress to summarize, or should we continue the conversation on dmtcp.slack.com?  Thanks.

**Comment by zhixuanc** [comment]
The issue is solved. Thank you for your patient help.

On Fri, Jul 31, 2015 at 8:16 PM, Gene Cooperman <notifications@github.com>
wrote:

> Hi @zhixuanc <https://github.com/zhixuanc> , we may have dropped the ball
> on this one. I've now issued an invite to you, on slack. @jiajuncao
> <https://github.com/jiajuncao>, what is the status on this issue with
> SLURM? Is there more progress to summarize, or should we continue the
> conversation on dmtcp.slack.com? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmtcp/dmtcp/issues/150#issuecomment-126839369>.
>



-- 
Zhixuan Cao
Mechanical Engineering, University at Buffalo SUNY

**Comment by gc00** [comment]
I'm closing this issue, since it's now been reported as solved.

**Comment by zhixuanc** [comment]
sure!

On Thu, Aug 27, 2015 at 12:22 PM, Gene Cooperman <notifications@github.com>
wrote:

> I'm closing this issue, since it's now been reported as solved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmtcp/dmtcp/issues/150#issuecomment-135483800>.
>



-- 
Zhixuan Cao
Mechanical Engineering, University at Buffalo SUNY
