### ISSUE TITLE
Disable ckpt on connect to coord, until wrappers initialized 

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#187]
When running `gdb --args dmtcp_launch -i2 a.out`, one can observe DMTCP crashing if one interactively traces `DmtcpWorker::DmtcpWorker()`.  In rare instances, this might also happen
to a user who is not running under `gdb`.

The fix should be easy.  Use `dmtcp_disable_ckpt()` before connecting to the coordinator, and then use `dmtcp_enable_ckpt()` later , robably near end of `DmtcpWorker::DmtcpWorker()` (and maybe we should verify that `dmtcp_prepare_wrappers()` has run before enabling??).

**Comment by karya0** [comment]
It's weird. This should already have been the case. If you look for `informCoordinatorOfRUNNINGState()`, you will notice that this was the intended purpose. May be a bug slipped or an oversight?

**Comment by gc00** [comment]
Pranay reported that this was a false alarm.  He can't reproduce this.  So, I'm closing the issue.
