### ISSUE TITLE
Interval checkpointing doesn't work when --daemon and --exit-on-last are both set for coordinator

### ISSUE THREAD

**Issue by jiajuncao** [dmtcp/dmtcp#191]
In this case, only manual checkpoint can be used. To reproduce the bug:

```bin/dmtcp_coordinator --daemon --exit-on-last```
```bin/dmtcp_launch -i 5 test/dmtcp1```

**Comment by rohgarg** [comment]
Just to clarify: the options when used separately do not cause this problem. The problem happens only when the two options are used together.

**Comment by rohgarg** [comment]
It looks like `SIGALRM` is not being delivered when the two options are used together. The signal handler seems to be set up correctly though.

**Comment by rohgarg** [comment]
Okay, I know the problem. We block all signals when the coordinator is started with the two options; we forgot to unblock `SIGALRM` when we switched to using `alarm()` recently. I'll push a patch soon.

**Comment by rohgarg** [comment]
It looks like my earlier analysis is incomplete. Interval checkpointing works if I start the coordinator explicitly, but does not work when it is started transparently using `dmtcp_launch`, i.e., `dmtcp_launch -i 5 a.out` is still broken.

**Comment by rohgarg** [comment]
Okay, I have figured it out:

When the coordinator is launched transparently by `dmtcp_launch`, the checkpoint interval is passed down as an environment variable, which is then set into the `theDefaultCheckpointInterval` global variable and the `theCheckpointInterval` global variable.  Now, `alarm()` gets called from `resetCkptTimer()`, which is called only if the two variables are unequal. As a result, the first call to `alarm()` is never made.

On the other hand, when the coordinator is launched explicitly, the `theDefaultCheckpointInterval` global variable is never set. When a user application connects to the coordinator, only the `theCheckpointInterval` global variable is set.

**Comment by gc00** [comment]
@rohgarg. do you know which commit broke this code.  If so, could you report the commit number?  This kind of post-mortem will help us build a better culture for robustness.  I'm not interested in the submitter, but just the commit number.  (People who make the effort to submit should always be rewarded, never penalized.  :-) )

**Comment by rohgarg** [comment]
@gc00: The problem was introduced in commit: 28102b4 that introduce the use of `alarm()`. Earlier we were using epoll timeouts for interval checkpointing, which didn't require any initial call or unblocking of `SIGALRM`.

**Comment by gc00** [comment]
Fixed via 5eaf023 (PR #201).
