### ISSUE TITLE
Support CMA (Cross Memory Attach)

### ISSUE THREAD

**Issue by jiajuncao** [dmtcp/dmtcp#218]
process_vm_readv() and process_vm_writev() were added in Linux 3.2 as a new method for data transfer between processes. Although they're nonstandard Linux extensions, some applications start to use them (e.g. MVAPICH2). We might need to support CMA eventually.

**Comment by karya0** [comment]
It should just require us to add the two wrappers to the PID plugin, correct? In that case, it should be pretty straight forward.

**Comment by gc00** [comment]
PR #221 fixes this issue.
