### ISSUE TITLE
Simplify DMTCP_TMPDIR environment variable

### ISSUE THREAD

**Issue by karya0** [dmtcp/dmtcp#24]
DMTCP_TMPDIR points to the directory where DMTCP places all temporary files.  This variable is inherited by all child processes and is passed as a command line flag to remote (ssh) children. 

Currently, DMTCP_TMPDIR is considered the root directory and we do not append anything to it. That is, if DMTCP_TMPDIR=/home/user/tmp, all temp files will end up in /home/user/tmp, even on remote nodes.  This could lead to unexpected behavior with some file such as sharedArea.* which expect a node-private tmp dir.

A potential fix is to always append dmtcp-USER@HOSTNAME to the passed DMTCP_TMPDIR.  This s the same suffix that we append to TMPDIR (or /tmp) if DMTCP_TMPDIR is not specified.

This also solves a problem related to restarted computation where the user might want to specify a different value for DMTCP_TMPDIR.  In this case, we can put the value of DMTCP_TMPDIR in SharedData which is later used by all child processes.

**Comment by gc00** [comment]
This improvement is now implemented in c36b15f7556490bf6e0095e0e73d3432dccacb17
