### ISSUE TITLE
Broken dmtcp_checkpoint() API on master

### ISSUE THREAD

**Issue by rohgarg** [dmtcp/dmtcp#313]
I didn't look at it closely but it seems like the `dmtcp_checkpoint()` API is broken on master. The program hangs after calling the checkpoint API.

**Comment by gc00** [comment]
Hmmm.  Again?  Is this on 2.5.0 or 3.0 or both?

**Comment by rohgarg** [comment]
@gc00: This is on the master, i.e., DMTCP-3.0. I investigated this further; it's the same issue as the one resolved by commit: 3dfd0ed8. We need a call to increment global counters: `numCheckpoints` and `numRestarts`.

@karya0: Since the new design doesn't use the `callbackPostCheckpoint()` function, do you know what's the right place to call `increment_counters()`?
