### ISSUE TITLE
Add InfiniBand detection

### ISSUE THREAD

**Issue by jiajuncao** [dmtcp/dmtcp#34]
When user forgets to enable IB plugin while running an IB application, we should print a warning message.

**Comment by karya0** [comment]
I just noticed a couple of issues with the patch.

1. This symbol is also declared in src/writeckpt.cpp.  Can we consolidate the two?

2. Currently you do the following test: `if (ibv_get_device_list && ibv_get_device_list(NULL) && !dmtcp_infiniband_enabled)`.  Why do we need to call `ibv_get_device_list(NULL)`? Aren't the remaining bits enough?

**Comment by jiajuncao** [comment]
@karya0 you're right. It's fixed now.
