### ISSUE TITLE
plugin-tutorial: reference to a deprecated event (DMTCP_EVENT_SUSPEND)

### ISSUE THREAD

**Issue by rohgarg** [dmtcp/dmtcp#35]
The plugin-tutorial doc mentions a DMTCP_EVENT_SUSPEND, but I couldn't find it anywhere in the source. I guess it's deprecated?

**Comment by gc00** [comment]
Sorry for the late reply.  I had listed the events about two years
ago.  Some of them have changed.  We should update the tutorial in github.

Best,
- Gene

**Comment by gc00** [comment]
This issue is fixed by 9426264e55ba66983b345354fdc1a326ab6028c4 .
