### ISSUE TITLE
dmtcp api for virtual to physical mapping in pathvirt

### ISSUE THREAD

**Issue by ankitcse07** [dmtcp/dmtcp#387]
Let me explain the requirement for such a API available for plugin writers.  

Assume that path virtualization is enabled and after restart,  process will perform path virtualization.  Now consider that restarted process connects to some external process which is not running under DMTCP.  On connection it sends some path which was present in virtual->physical mapping
This would be problem for external process as it would not perform path mapping. 

 This can be solved if restarted process can query for the physical mapping and accordingly send the new path to external process. 

PathVirt plugin already has same api but that is not exposed, can this API be exposed similar to other DMTCP APIs.

**Comment by rohgarg** [comment]
I think I'm okay with this.

**Comment by ankitcse07** [comment]
#388  Please review the code

**Comment by ankitcse07** [comment]
a771f09 commit done, closing this Issue
