### ISSUE TITLE
Segfault when using ltdl

### ISSUE THREAD

**Issue by kwharrigan** [dmtcp/dmtcp#411]
I started a mailing list topic on this w/r to ImageMagick's "convert" crashing, which I've reduced down to a trivial test case involving use of libtool / ltdl.  Apologize for the delay in getting this submitted. 

@rohgarg suggested running with disable-alloc-plugin, and that works, so presumably the issue is in there somewhere. 

Have a look at https://github.com/kwharrigan/dl_vs_ltdl.   You can run `make dmtcp_test` and should get a segfault when trying to run the ./ltdl under dmtcp_launch

**Comment by rohgarg** [comment]
@kwharrigan: Sorry about the extremely long delay on this. I think we have a solution to this problem now. The PR #347 and a few other patches on top of that will address this issue.

**Comment by rohgarg** [comment]
Fixed via PRs #444 and #456.
