### ISSUE TITLE
Build Error on Armv7l 

### ISSUE THREAD

**Issue by nkigen** [dmtcp/dmtcp#424]
Hi, I'm encountering errors when trying to build DMTCP directly on an armv7l zedboard running archlinux arm (without cros-compiling).
Here's what I do
`./configure`
`make`

I get errors related to expansion of macros in certain files ([see here](https://gist.github.com/nkigen/1b721d3b4a51d3f8eada4c3650c8fe81))

[Here is](https://gist.github.com/nkigen/3270fc8ed19f4ad697b7f98fbfd3f539) config.status 

What could the problem be?`

**Comment by rohgarg** [comment]
@nkigen: What platform is this? You might need the `-march=native` compiler flag. Here's what I do on Raspberry Pi-2 (which is ARMv7l):
 ```
./configure CFLAGS='-march=native' CXXFLAGS='-march=native'
```
This is with GCC-4.8.

**Comment by nkigen** [comment]
@rohgarg Its a xylinx zedboard. I just tried `./configure CFLAGS='-march=native' CXXFLAGS='-march=native'` and still got the same error.. 

I'm using gcc5.3

**Comment by gc00** [comment]
Hi all,
    I think I've seen something similar, but I've forgotten the details.
I think the key points were:
> mtcp_sys.h:486:35: error: expected expression before ')' token
>       mtcp_syscall(SYS_##name, args)
>                                    ^
> mtcp_sys.h:258:35: note: in expansion of macro 'mtcp_inline_syscall'
> #define mtcp_sys_getpid(args...) mtcp_inline_syscall(getpid,0)

If I remember correctly, the wrong .h file or the wrong macro
definition was being loaded.  I'll think more about this, and see
if I can remember something.  We were using the Ubuntu ARM distribution.

Best,
- Gene

**Comment by nkigen** [comment]
@gc00 Yes those are the key points. Thanks I'll greatly appreciate your help. I'm currently trying to evaluate DMTCP for potential use in our Dependable and Distributed Aerospace Middleware suite but I'm stuck as I can't get it to compile on our test platform.

**Comment by gc00** [comment]
Hi Nelson,
    My colleague reminded me.  (I should have remembered.)  We had
recently discovered a regression for ARM.
    Have you tried out the development branch from
  http://dmtcp.sourceforge.net/downloads.html
    Specifically, could you try:
  git clone --branch=2.5 https://github.com/dmtcp/dmtcp.git dmtcp-dev

Let us know if that works for you.  If for some reason it doesn't,
is there an easy way to give us the ability to ssh to your
ARM computer with a guest account?  If so, then I could analyze
this issue directly, and report back to you.  (And of course, any
account info should be sent only by a private e-mail.)

Best,
- Gene

**Comment by nkigen** [comment]
@gc00 It worked!! Thanks so much for your help. I'll go ahead and try it out now.
