### ISSUE TITLE
BUG diagnosis: User files saved in DMTCP_TMPDIR are being blacklisted.

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#48]
DMTCP_TMPDIR and TMPDIR can coincide.  A user will put files in TMPDIR, and DMTCP considers that all files in DMTCP_TMPDIR are owned by DMTCP.  This bug apparently affects any user who sets DMTCP_TMPDIR or who uses the --tmpdir flag of dmtcp_launch.  In particular, it affects test/file1, and it affects Open MPI version 1.6.

The following fails:
    DMTCP_TMPDIR=/tmp/dmtcp-gene@dekaksi make check-file1

This issue is that test/file1 creates and then unlinks a file while 
continuing to use the file descriptor pointing to it.

Apparently, _isBlacklistedFile() considers this _user_ file to be
blacklisted because it is in DMTCP_TMPDIR, and the program logic assumes
that all files in DMTCP_TMPDIR are owned by DMTCP.

Because the file is blacklisted, the file type is never set to FIKLE_DELETED.
So, on restart, the restart fails.

In order to demonstrate this diagnosis, try for example:
  DMTCP_TMPDIR=/tmp/dmtcp-USER@HOST make check-file1
and restart will fail.
Then go to: FileConnection::handleUnlinkedFile() and comment out the call to !_isBlacklistedFile(_path), and the bug will go away when again executing:
  DMTCP_TMPDIR=/tmp/dmtcp-USER@HOST make check-file1

I'll need to think carefully about a re-design of the file plugin to fix this.  Any suggestions are welcome.

**Comment by gc00** [comment]
I'm thinking that DMTCP_TMPDIR should be the base directory, and DMTCP_TMPDIR/dmtcp-USER@HOST should be calculated by us internally.  So, the help in configure/dmtcp_launch would be modified, get_tmp_dir(), and the rm plugin uses DMTCP_TMPDIR directly.  We should also check what happens if DMTCP_TMPDIR is not present upon launch, upon restart, etc.  I'll go forward with this, if I don't hear anything.

**Comment by karya0** [comment]
DMTCP_TMPDIR should _NOT_ be the base directory. The base directory is supposed to be TMPDIR.  DMTCP_TMPDIR is just a convenience variable to provide an alternate to TMPDIR/dmtcp-user@host.

Having said that, the files in DMTCP_TMPDIR are usually open on the protected-fds (fd >821) and so they won't be checkpointed anyways by DMTCP and so we should be able to remove the `-      Util::strStartsWith(path, dmtcp_get_tmpdir())) {` line from the isBlacklisted() function.

I don't know what is the use of DMTCP_TMPDIR for the RM plugins, but there also, we should be able to use a protected-fd (or equivalent).  Ideally, the RM plugin (or any other plugin) shouldn't rely on DMTCP_TMPDIR; they are free to use their own stuff.

**Comment by karya0** [comment]
Any thoughts @artpol84 ?

**Comment by gc00** [comment]
> DMTCP_TMPDIR should _NOT_ be the base directory.
Yep, I agree.  That's exactly my point, too.  The problem is that in
the current design, the end user does assume that DMTCP_TMPDIR is a
base directory.  That's what happened in the recent bug report.

The problem is that DMTCP_TMPDIR currently looks like a base directory,
and yet it refers to the DMTCP internal directory.  So we're exposing
DMTCP internals to the end user, thereby inviting end users to mess with
the internals of DMTCP.

Basically, I'm arguing for two versions of DMTCP_TMPDIR.  The DMTCP_TMPDIR
that's a base directory (e.g., /tmp) will be an environment variable
exposed to the end user.  Inside DMTCP, we will immediately convert to
our internal tmp directory corresponding to:  TMPDIR/dmtcp-user@host.

If we do it this way, we don't have to remove the
Util::strStartsWith(path, dmtcp_get_tmpdir()))  from the isBlacklisted()
function.  Keeping that line in, seems more robust in terms of looking
at the future.

As for the rm plugin, my proposal is that we could start with
the user version (DMTCP_TMPDIR as a base directory), and then add
a dmtcp-USER@host-rm subdirectory (just as we currently add a
dmtcp-USER@host subdirectory).

**Comment by karya0** [comment]
>
> The problem is that DMTCP_TMPDIR currently looks like a base directory,
> and yet it refers to the DMTCP internal directory. So we're exposing
> DMTCP internals to the end user, thereby inviting end users to mess with
> the internals of DMTCP.
>
> Basically, I'm arguing for two versions of DMTCP_TMPDIR. The DMTCP_TMPDIR
> that's a base directory (e.g., /tmp) will be an environment variable
> exposed to the end user. Inside DMTCP, we will immediately convert to
> our internal tmp directory corresponding to: TMPDIR/dmtcp-user@host.
>
> If we do it this way, we don't have to remove the
> Util::strStartsWith(path, dmtcp_get_tmpdir())) from the isBlacklisted()
> function. Keeping that line in, seems more robust in terms of looking
> at the future.
>

I would say that we shouldn't expose DMTCP_TMPDIR or any equivalent thing
to the end user at all.  In fact, with the newer code, the DMTCP_TMPDIR env
var is not used by DMTCP except during dmtcp_launch, dmtcp_restart and
dmtcp_coordinator.  I would suggest that we unset DMTCP_TMPDIR right away
after using it in dmtcp_launch, etc.

For the base directory, the user code should be using TMPDIR or /tmp if
TMPDIR is not available.  Now that we are talking about this, I would
suggest that we completely hide DMTCP_TMPDIR from the end user, they don't
have any use for it. They can control this indirectly by setting TMPDIR.

**Comment by gc00** [comment]
> For the base directory, the user code should be using TMPDIR or /tmp if
> TMPDIR is not available.  Now that we are talking about this, I would
> suggest that we completely hide DMTCP_TMPDIR from the end user, they don't
> have any use for it. They can control this indirectly by setting TMPDIR.

A few other systems offer a customized version of TMPDIR.  It's
intended only for cases when the default TMPDIR is not appropriate.
In those cases, their customized version defaults to TMPDIR.

For example, maybe they're worried that TMPDIR might not always point to
a valid directory when their software is copied to new sites.  As one
example, suppose they're running an HPC application in a batch queue where
policy forbids using /tmp, then they set DMTCP_TMPDIR to point inside
the main DMTCP directory.  This was the core intuition being used when
this bug appeared in the recent bug report.  This is a valid use case,
and in this case, they wouldn't want the general TMPDIR pointing inside
the main DMTCP directory.  They just want to re-direct DMTCP_TMPDIR.

The extra code to support this is tiny, and it's already there inside DMTCP.

**Comment by karya0** [comment]
In that case can't they define their own TMPDIR variable? I am worried about providing a service that we are not fully ready to support.  Let's keep it simple and let users figure out a way to get their own TMPDIR. We'll just use the TMPDIR to calculate DMTCP_TMPDIR for DMTCP use only.

**Comment by gc00** [comment]
> Let's keep it simple and let users figure out a way to get their own TMPDIR
Sorry for writing a long answer.  Maybe we should move this discussion
from e-mail to the phone.  It will be more efficient.

Anyway, here are the details:

We save four lines of code by keeping it simple for DMTCP.  We then create
a lot of pain for users who can't predict ahead of time the environment
where they'll be using DMTCP.  This use case happens in HPC batch jobs,
in Condor, in large companies where the central IT offers a persistent
desktop for engineering applications, and various other examples.
I've had these discussions with DMTCP "customers".

Currently, DMTCP uses dmtcp_get_tmpdir(), which uses sharedData::getTmpDir().
We can initialize the sharedData to try TMPDIR and then /tmp
or initialize the sharedData to try DMTCP_TMPDIR, then TMPDIR, then /tmp.

It takes us about two extra lines of code to try DMTCP_TMPDIR, and about
two more lines of code to keep our current --tmpdir flag in dmtcp_launch.

If we don't provide this, we ask end users to write their own error-prone
code in which they probe for whether TMDPIR or /tmp is available, and
if not, they should set TMPDIR to the dmtcp main directory just before
using DMTCP, and then set TMPDIR back to its default when they're not
using DMTCP.  So, we save four lines, and the user has a problem that's
far from simple.

**Comment by karya0** [comment]
I think we are discussing two somewhat separate issues here:

1. How to calculate "tmpdir" for storing stateless session files (shareddata files, etc.)?
2. Whether or not to expose DMTCP_TMPDIR to the end user.

For (1), the current approach is to use "--tmpdir" (DMTCP_TMPDIR), $TMPDIR/dmtcp-user@host, and /tmp/dmtcp-user@host, in that order.  I am arguing here that we should discourage users from using "--tmpdir" flag and that DMTCP should be using TMPDIR to calculate DMTCP_TMPDIR.

I guess your concern is that TMPDIR may not be set or may be invalid.  This, I would argue, suggest a larger problem in the system.  According to http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03, _most_ programs/shells/commandline interpreters would set TMPDIR to point to the correct location.

Having said that, if we want to be extra careful, let's keep "--tmpdir" flag, but make the help message more explicit:
- Directory to store temporary files
+ Set the root for the session directory tree for DMTCP ONLY.

(This "Set the ..." is inspired from OpenMPI's help message for --tmpdir.)

For (2), I strongly suggest that DMTCP_TMPDIR must not be used to user programs. In fact, it should be unset as soon as we have calculated the tmpdir for DMTCP's internal use. DMTCP plugins can use `dmtcp_get_tmpdir()` function to get the tmpdir used by DMTCP.

Does this sound reasonable?

**Comment by gc00** [comment]
Can we talk about this on the phone?  It's faster than e-mail.

Anyway, if you want to see a real-world use case, look at this:
  http://www-01.ibm.com/support/knowledgecenter/SSETD4_9.1.2/lsf_config_ref/lsf.conf.lsf_tmpdir.5.dita
It's about how to use LSF_TMPDIR for LSF batch queues.  I promise that I've
encountered other cases in my own work.

If we're now saying that we'll keep --tmpdir (with the motivation that
Open MPI offers it) and remove DMTCP_TMPDIR (with the motivation that
LSF offers it and we don't like the LSF model), then we're now talking
about removing _two lines of code_ from DMTCP to make DMTCP easier to
maintain for the developers.

Yes, there's a Linux standard that says that TMPDIR should point to
a reasonable choice on any well-configured Linux system.  Unfortunately,
not all systems are well-configured, and HPC batch queues sometimes want
to do funny things with their file hierarchy.

In the past, DMTCP provided DMTCP_TMPDIR for just these occasions.
We had a design bug in letting DMTCP_TMPDIR default
to $TMPDIR/dmtcp-USER@HOST .  The rest of the world would have designed
DMTCP_TMPDIR to default to TMPDIR.  I want to change DMTCP_TMPDIR to
default to TMPDIR.

The upside of my proposal is:
*  We don't break the code of users currently using DMTCP_TMPDIR, and we
   allow new users to employ well-developed paradigms in HPC job queues.

The downside of my proposal is:
*  We have to continue to maintain the two lines of code in DMTCP
   that already exist today.

Is there another downside of letting DMTCP_TMPDIR default to TMPDIR?

Anyway, let's talk on the phone.  We've spent much too much time
discussing whether we should remove two lines of code in DMTCP.

**Comment by karya0** [comment]
Sure. We can then summarize our conclusion here.

**Comment by gc00** [comment]
[ Kapil and I had gotten into some weird tight loop in the e-mail.  But it
  turns out that we both agree on the basic principles and how to proceed.
  Here is the summary. ]

1.  If DMTCP_TMPDIR is not set and the user calls:
      dmtcp_launch --tmpdir /tmp/mydir
    then DMTCP currently saves /tmp/mydir in its sharedData and also sets
    the environment variable DMTCP_TMPDIR to /tmp/mydir.
    We should not be setting DMTCP_TMPDIR if it wasn't set originally,
    and so a new commit will make sure that we don't set DMTCP_TMPDIR.

2.  If the user has set DMTCP_TMPDIR or TMPDIR or used --tmpdir,
    then we will interpret that directory as a _base_directory_.
    Internally in DMTCP (not visible to end user), we will expand
    that into:  base_directory/dmtcp-USER@HOST
    That expanded directory name will be saved in sharedData.
    All reference to dmtcp-USER@HOST (e.g., dmtcp_launch --help)
    will be removed.

3.  In the future, some user may use DMTCP for process migration and
    discover that their DMTCP_TMPDIR value was available on the source
    machine, but is not available on the destination machine.
    This is a separate issue, which will be the responsibility of
    the end user.  They can change their tmpdir using: dmtcp_restart --tmpdir
    Or they can let DMTCP choose a new default (DMTCP_TMPDIR or TMPDIR
    or /tmp).  DMTCP will use the new _base directory_ in combination
    with dmtcp-USER@HOST on restart.  If the user also uses their
    specified tmpdir, then it's the user's responsibility to realize
    that after process migration, the destination host may or may not
    have available the original tmpdir that the user may have cached
    inside the user code.
        In the future, we'll also write a plugin to easily virtualize
    filename prefixes, so that they can use that plugin with some
    configuration file like:  /tmp -> /tmp2
    (Actually, I'm thinking of a more subtle design, but this will
    be a separate issue.)

4.  The script plugin/batch-queue/dmtcp_rm_loclaunch.sh
    sets DMTCP_TMPDIR as a _shell variable_.  It doesn't export it as
    an environment variable.  We'll change this to the shell
    variable, dmtcp_tmpdir.  We'll initialize the shell variable
    to either DMTCP_TMPDIR or TMPDIR or /tmp (whatever is available).
    The script can then continue to append to dmtcp_tmpdir .

**Comment by gc00** [comment]
Commits  78dcc4abdf737b13ee6e4b30490117fd1025742c and  c36b15f7556490bf6e0095e0e73d3432dccacb17 and   0f9e2a5919b8a3f41fa6451bc6248f37d463ae95  implement the fix and enhancements.
