### ISSUE TITLE
dmtcp_command -k: exit() or _exit()?

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#51]
Currently, 'dmtcp_command -k' causes the application to execute "_exit()".  (See coordinatorapi.cpp)  Because we call _exit() instead of exit(), pending buffer output is not flushed (glibc:_cleanup() not called), and any user atexit() functions are not called.  Shouldn't we be calling exit() to respect the user's intentions?
    The user might have registered an atexit() fnc that goes into an infinite loop, but I believe it's not up to us to protect the user from their own mistakes.  Any user seeing this will soon discover that they registered a buggy atexit function.

**Comment by karya0** [comment]
That's a good point. We should always be calling `_real_exit()` instead of `_exit()` except when the exit is coming from DMTCP itself i.e. JASSERT, etc.

**Comment by gc00** [comment]
There are two occurences of _exit in coordinatorapi.cpp.
Shall I change them both to _real_exit() and commit,
  or should I do a pull request?  (Dangerous, in my case.  :-) )

**Comment by karya0** [comment]
On Wed, Apr 1, 2015 at 7:56 PM, Gene Cooperman <notifications@github.com>
wrote:

> There are two occurences of _exit in coordinatorapi.cpp.
> Shall I change them both to _real_exit() and commit,
> or should I do a pull request? (Dangerous, in my case. :-) )
>

Let's commit this directly (without a pull request), but include a
"resolves #51" in the commit message. This will automatically close the
issue (https://help.github.com/articles/closing-issues-via-commit-messages/
).

Kapil
