### ISSUE TITLE
dmtcp_launch hangs on RHEL5 and RHEL6

### ISSUE THREAD

**Issue by aparashk** [dmtcp/dmtcp#537]
I have experienced problems getting a working build of DMTCP 2.5.0 final tag on Redhat/Centos Linux.

`dmtcp_launch` hangs when executed with a binary for checkpointing. This is easy to replicate on both 32-bit and 64-bit installs of RHEL6/Centos6 (Centos5 first requires a patch as DMTCP depends on a newer version of `binutils` than what Centos5 provides):

`./configure ; make ; make check`

hangs on both OSes. The same sequence works on Ubuntu 12.04 and 14.04 and all testcases pass.

**Comment by rohgarg** [comment]
@aparashk: Thanks for reporting this. I'll look into this.

**Comment by aparashk** [comment]
Thank you for the amazing support!

**Comment by rohgarg** [comment]
Fixed via PR's #539 (for 2.4 and 2.5) and #540 (for 3.0).
