### ISSUE TITLE
Document implicit dependence on binutils version

### ISSUE THREAD

**Issue by aparashk** [dmtcp/dmtcp#538]
I have found that, somewhere between DMTCP 2.4.5 and DMTCP 2.5.0, or more specifically in [this commit](https://github.com/dmtcp/dmtcp/commit/72be59c8658d4e1fe57899e7ed42b3ed8993cecf), DMTCP started to require a newer version of binutils than some legacy Linux distributions, for example Redhat 5, come with. More specifically, this is due to the use of the STT_GNU_IFUNC macro.

It would be good for the binutils version dependence to be documented somewhere.

**Comment by rohgarg** [comment]
@aparashk: Good catch! We should definitely fix this.

**Comment by rohgarg** [comment]
@aparashk: I have a preliminary patch that seems to work. It's still a work-in-progress though. Could you please check if this is sort-of-correct? (This is on top of the 2.5 branch.)

```patch
diff --git a/src/dmtcp_dlsym.cpp b/src/dmtcp_dlsym.cpp
index 1485c6da..804b24b1 100644
--- a/src/dmtcp_dlsym.cpp
+++ b/src/dmtcp_dlsym.cpp
@@ -356,6 +356,8 @@ void *dlsym_default_internal_library_handler(void *handle, const char*symbol,
   *default_symbol_index_p = default_symbol_index;
 
   if (default_symbol_index) {
+#if __GLIBC_PREREQ(2, 11)
+    // See https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Function-Attributes.html
     if (ELF64_ST_TYPE(tags.symtab[default_symbol_index].st_info) ==
         STT_GNU_IFUNC) {
       typedef void* (*fnc)();
@@ -363,8 +365,8 @@ void *dlsym_default_internal_library_handler(void *handle, const char*symbol,
                      tags.symtab[default_symbol_index].st_value);
       return f();
     } else {
-      return tags.base_addr + tags.symtab[default_symbol_index].st_value;
-    }
+#endif
+    return tags.base_addr + tags.symtab[default_symbol_index].st_value;
   } else {
     return NULL;
   }
diff --git a/src/plugin/ipc/event/eventconnection.cpp b/src/plugin/ipc/event/eventconnection.cpp
index 0dec27cc..6e4e1b5c 100644
--- a/src/plugin/ipc/event/eventconnection.cpp
+++ b/src/plugin/ipc/event/eventconnection.cpp
@@ -77,7 +77,9 @@ void EpollConnection::postRestart()
   if (_size != 0) {
     tempFd = _real_epoll_create(_size);
   } else {
+#if __GLIBC_PREREQ(2, 9)
     tempFd = _real_epoll_create1(_flags);
+#endif
   }
   JASSERT(tempFd >= 0) (_size) (_flags) (JASSERT_ERRNO);
   Util::dupFds(tempFd, _fds);
diff --git a/src/threadlist.cpp b/src/threadlist.cpp
index f5bb2458..566f1297 100644
--- a/src/threadlist.cpp
+++ b/src/threadlist.cpp
@@ -689,10 +689,12 @@ void ThreadList::waitForAllRestored(Thread *thread)
 void
 ThreadList::postRestartDebug(void)
 { // Don't try to print before debugging.  Who knows what is working yet?
+  // User should have done GDB attach if we're here.
+#ifdef HAS_PR_SET_PTRACER
   int dummy = 1;
   while (dummy);
-  // User should have done GDB attach if we're here.
   prctl(PR_SET_PTRACER, 0, 0, 0, 0); // Revert permission to default: no ptracer
+#endif
   postRestart();
 }
 
diff --git a/test/epoll1.c b/test/epoll1.c
index cd71cbef..6e8afd9a 100644
--- a/test/epoll1.c
+++ b/test/epoll1.c
@@ -26,7 +26,11 @@ void server()
   int conn_sock, nfds, epollfd;
 
   if (use_epoll_create1 == 1) {
+#if __GLIBC_PREREQ(2, 9)
     epollfd = epoll_create1(EPOLL_CLOEXEC);
+#else
+    epollfd = epoll_create(5);
+#endif
   } else {
     epollfd = epoll_create(5);
   }
```

**Comment by gc00** [comment]
@aparashk, Are the three modifications the only cases where you found the need for a patch?  If so, we can take these three cases and continue to polish them.

@rohgarg, Would you mind testing this patch provided by @aparashk?  I propose that we include this for versions 2.5.1 and 3.0/master.  If this is also easy to apply to version 2.4.8, we can include it.  Otherwise, we should go ahead with the planned 2.4.8 release now, and add this to the 2.4 branch for later.

**Comment by rohgarg** [comment]
@gc00: There appears to be some confusion here. This was a patch I provided to @aparashk for testing. I have cleaned up the patch and created a PR now.

**Comment by rohgarg** [comment]
Fixed via PRs #562 and #563.

**Comment by aparashk** [comment]
Hello,

I am sorry I have not had a chance to try this patch. All I had to do to resolve this issue with DMTCP 2.5.0 release is to remove the reference to the STT_GNU_IFUNC macro, via the following:

#ifndef STT_GNU_IFUNC
#define STT_GNU_IFUNC 10
#endif

Since I do not see a reference to STT_GNU_IFUNC in this patch, I would say the patch will not resolve the issue on Centos 5 and other distributions with an older version of binutils.


Best regards,
    Atanas

**Comment by rohgarg** [comment]
>Since I do not see a reference to STT_GNU_IFUNC in this patch, I would say the patch will not resolve the issue on Centos 5 and other distributions with an older version of binutils.

The patch does ifdef out the reference to `STT_GNU_IFUNC` for older distributions/libc so it _will_ resolve the issue.  I have tested this on CentOS 5. The rationale is that on older distributions/libc you will not have symbols of type `STT_GNU_IFUNC` and so you needn't worry about resolving such symbols; defining your own version of `STT_GNU_IFUNC` for older distros is not required.
