### ISSUE TITLE
File doesn't have .dmtcp extension

### ISSUE THREAD

**Issue by SenthilCaesar** [dmtcp/dmtcp#589]
I am trying to restart the checkpoint script  ./dmtcp_restart_script.sh and it produces the below error.

[21083] NOTE at dmtcp_restart.cpp:827 in main; REASON='File doesn't have .dmtcp extension. Check Usage.'

Ran the script in debug mode, Inside the dmtcp_restart_script.sh the issue is that the double quotes around the coord_logfile is causing this issue. If I get rid of that double quotes the script runs without any error.

if [ -n "$localhost_ckpt_files_group" ]; then
exec $dmt_rstr_cmd --coord-host "$coord_host" --coord-port "$coord_port" "$coord_logfilogfile" \
  $ckpt_dir $maybejoin --interval "$checkpoint_interval" $tmpdir $noStrictChecking $localhost_ckpt_files_group
fi

sh -x dmtcp_restart_script.sh
+ exec /share/apps/dmtcp/2.5/bin/dmtcp_restart --coord-host chimera01.chimera.local --coord-port 7779 '' --interval 300 /home/senthil.palanivel001/checkpoint/ckpt_fft_openmp_19118b8b9fc9ee72-40000-97eb04225aa39b.dmtcp

Could someone help us fix this issue

**Comment by rohgarg** [comment]
Thanks for reporting this issue, @SenthilCaesar. As you noted, this appears to be a bug in the restart script. We can definitely fix this for the next release.
