### ISSUE TITLE
--enable-m32 doesn't work standalone

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#62]
`./configure --enable-m32` is supposed to work standalone, not just as part of a multi-arch build.  Currently, to make it work, one must do something like:
 `make -j clean && rm -rf bin lib && make -j && (cd src && make -j || true) && 
    (cp -prf lib/dmtcp/32/bin/ bin || true) &&
   make -j check-dmtcp1`
to make `--enable-m32` work with all DMTCP commands built for m32.  We should modify the make files to do this automatically, and `rm -rf bin lib` as necessary if this is part of a multi-arch build.
[ In addition to supporting other users, it makes it much easier for the developers to test m32 mode. ]

**Comment by karya0** [comment]
At the first read, your argument sounds convincing.  However, this is rather confusing from the point of view of packaging. As of our current design, there are no 32-bit binaries (except mtcp_restart_32), only 32-bit libraries. Commands like dmtcp_launch and dmtcp_restart automatically do the correct thing by linking the required 32/64 bit libraries as needed. In essence, the 32-bit libraries are supposed to act as auxiliary units for the 64-bit binaries and libraries.

Having said that, we definitely need something to improve automated build of 32-bit binaries. One possibility is to write a short script to put in util/ that builds 64-bit and 32-bit rather seamlessly. Any thoughts?

**Comment by gc00** [comment]
I encountered this issue in trying to do a 'git bisect'
through the history, using --enable-m32.  I have a version
of what mostly works in my testing, as part of my pull request
for git-bisect-example (git-bisect-m32.sh).  The core is:

`./configure --enable-m32 && make -j clean && rm -rf bin lib && (PATH=$PATH:. make -j) && \
  make -j clean && rm -rf bin lib && make -j && (cd src && make -j || true) && \
    (mkdir -p bin && cd bin && ln -sf ../lib/dmtcp/32/bin/* ./ || true) && \
    (cd lib/dmtcp && ln -sf 32/lib/dmtcp/* ./ || true) && \
    (cd lib/dmtcp/32/bin && ln -s mtcp_restart-32 mtcp_restart || true) && \
  make -j check-dmtcp1`

If we had --enable-m32 do this, it should work standalone.
(The link of `mtcp_restart-32` to `mtcp_restart` is not needed.  That's
only for an older revision.)

I believe that this version of --enable-m32 would not interfere
with our multi-arch build.  I would test the multi-arch build as
part of this enhancement.

Should I move forward and cause --enable-m32 to also work correctly
for standalone m32 builds?

**Comment by gc00** [comment]
I found the bug fix affecting standalone launch for m32.  This bug fix (commit 9445ba7ef682876ad09483e31c4c6e5f10556289 ) affects only standalone m32, and not multi-arch.
There is still a bug for restart with m32.  That affects both this issue and issue #61 .

When this last bug is resolved, we still need to discuss the proper enhancement so that --enable-m32 will produce a standalone m32 version of DMTCP.

**Comment by gc00** [comment]
Pull request #71 will resolve this for now.  Note that there will be opportunities in the future to simplify that work.  Quoting from pull request #71:

As a separate comment, I'll note that this pull request requires ENABLE_VDSO_CHECK to be defined.  Eventually, we may be able to get rid of that by separately including inline certain functionality from mtcp_check_vdso().  Probably we'll have to worry about two issues:
`mtcp_sys_personality((pers | ADDR_NO_RANDOMIZE) & ~ADDR_COMPAT_LAYOUT)`
and making sure that we are using the `AT_SYSINFO` vector correctly.

**Comment by gc00** [comment]
When master is combined with pull request #72, we now have the recipe:
`./configure --enable-m32 CXXFLAGS="-g3 -O0" && make -j clean && rm -rf lib bin && make -j && (cd src && make -j) && (cd lib/dmtcp && ln -s 32/lib/dmtcp/* ./) && (mkdir -p bin && cd bin && ln -s ../lib/dmtcp/32/bin/* ./) && make -j check`
This is excellent progress! (By the way, note that an m32 build can never checkpoint a 64-bit app, and so some tests will always fail.)
Standalone m32 is now failing on second checkpoint, which seems to be a new bug, but let's check in this restart fix, so that we have firm ground on which to build.

There have been times in the recent past when standalone m32 was working, but since the recipe is so complicated, I suspect that other commits were breaking standalone m32.  Now that the number of pull requests is starting to go down again, I'm hoping that we can achieve stability on standalone m32.

**Comment by gc00** [comment]
@rohgarg and @karya0:  Great news!   I tried the recipe above for CentOS 7, and it's now working in standalone 32-bit mode, when I include the pending pull request #71.  So, soon the master branch will fully support standalone 32-bit mode again.  The last time that DMTCP could support 32-bit standalone was way back in DMTCP-2.4.0.

It passes all of the tests except for dlopen1.  But we already knew that the dlopen1 test exposes a different bug.

**Comment by gc00** [comment]
Pull request #105 closes this issue.  As noted there, a new issue, #108, has been created for the high-level design ideas for M32
