### ISSUE TITLE
Segmentation fault at launch DMTCP 2.4.8 on redhat 6.6

### ISSUE THREAD

**Issue by harryj** [dmtcp/dmtcp#620]
So we are testing dmtcp on a program for someone else and we don't have consistent access to the machine the test is run on. Some time after starting dmtcp_launch (but before any checkpointing) the program seg faults and we're trying to figure out why. I know the next step would be to run gdb to see what's going on but is there any way to analyze the core dump file? Which executable would we use in that case, dmtcp_launch or the main program being run?

Any suggestions or advice is appreciated.

On a side note, the program doesn't seg fault when run without dmtcp.

**Comment by rohgarg** [comment]
Hi @harryj: Sorry about the late reply. Since this is a pre-checkpoint issue, you can directly run under GDB to capture the stack trace.

    $ gdb --args dmtcp_launch <dmtcp-args> /path/to/your/program <program-args>
    ...
    (gdb) run
    (gdb) thread apply all bt

For the coredump, you should use the program executable.

    $ gdb /path/to/your/program corefile
    ...
    (gdb) thread apply all bt

**Comment by harryj** [comment]
Hi Rohan, thanks for responding! 

So from the stack trace it looks like the seg fault is caused by a call to readdir64 in libc. It says there are no symbol tables available so I can't see more than that. I can try to include the debug symbols from libc to get more information about the arguments and local vars and where in readdir64 the error happens.

Some more information: the main process runs for a while and does some fifo stuff, then forks a child process. The child process then calls readdir64 and that's where the seg fault happens. 

Like I mentioned before, the program runs fine when run without dmtcp. As far as I know, dmtcp doesn't wrap readdir or readdir64, but it does wrap opendir, which gets called before and whose output is passed into readdir64 so perhaps the issue is in something dmtcp does with opendir? If you have any other ideas what the issue I'd love to hear them. Thanks again.

**Comment by rohgarg** [comment]
I don't see any obvious issue from your description. It seems like it's the child process that segfaults.

Could you please share the stack trace?

One way to get the trace would be to follow the child process. For this, you'd have to run directly under GDB and type `set follow-fork-mode child` before the fork call. With this, GDB will attach itself to the child process when it gets forked. Finally, when the child process crashes with a segfault, you'd have to type: `thread apply all bt`

However, if you have a core dump, that should work as well. You can use the command from my last comment. In case the application forks and execs into a different program than the parent, you'd have to use that for the executable.
