### ISSUE TITLE
Getting error "Cannot figure out glibc version" on dmtcp_launch

### ISSUE THREAD

**Issue by hprocpoint** [dmtcp/dmtcp#832]
Trying to run dmtcp on redhat 7.6 x86_64 with glibc 2.17-260. Any help would be greatly appreciated, thanks!

**Comment by gc00** [comment]
Hi @hprocpoint , Can you give us a few more clues.  :-)

First of all, I search through the DMTCP source, and I'm not seeing:
  "Cannot figure out glibc version"
from DMTCP.  Are you sure that message is coming from DMTCP?

Next, for more information, which version of DMTCP are you using?   One easy way to provide full information is:
  `make display-build-env`

Second, did you try:
  `make check`
OR a shorter version is just one test:
  `make check-dmtcp1`

If those checks are failing, do they fail on launch, ckpt, or restart?  For more verbose information, please try:
  `bin/dmtcp_launch -i5 test/dmtcp1`

Thanks.

**Comment by hprocpoint** [comment]
Hi, we realized it was an error coming from the application itself not dmtcp. Thanks though!
