### ISSUE TITLE
dmtcp2.6 cannot run hip program

### ISSUE THREAD

**Issue by yulingao** [dmtcp/dmtcp#996]
Hi, I try to dmtcp_launch a hip program with dmtcp2.6, but the program gets stuck somewhere. 
When I don't use dmtcp_launch, it can run correctly.

**Comment by gc00** [comment]
What do you mean by HIP?  If it's the AMD library for GPU computing, we don't support that.  Also, please try DMTCP main branch, which will soon be DMTCP 3.0.
